[package]
name = "types"
version = "0.6.0"
edition = "2018"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
marine-rs-sdk = { workspace = true }
eyre = "0.6.8"
